/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setSearchParams, toPathString, createRequestFunction } from './common';
// @ts-ignore
import { BASE_PATH, BaseAPI, operationServerMap } from './base';
/**
 * DefaultApi - axios parameter creator
 * @export
 */
export const DefaultApiAxiosParamCreator = function (configuration) {
    return {
        /**
         *
         * @summary Get Balance And Group By Address
         * @param {string} address
         * @param {boolean} [mempool]
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getBalanceAndGroupByAddressStatsAddressesGet: async (address, mempool, options = {}) => {
            // verify required parameter 'address' is not null or undefined
            assertParamExists('getBalanceAndGroupByAddressStatsAddressesGet', 'address', address);
            const localVarPath = `/stats/addresses`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = Object.assign(Object.assign({ method: 'GET' }, baseOptions), options);
            const localVarHeaderParameter = {};
            const localVarQueryParameter = {};
            // authentication APIKeyHeader required
            await setApiKeyToObject(localVarHeaderParameter, "x-api-key", configuration);
            if (address !== undefined) {
                localVarQueryParameter['address'] = address;
            }
            if (mempool !== undefined) {
                localVarQueryParameter['mempool'] = mempool;
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = Object.assign(Object.assign(Object.assign({}, localVarHeaderParameter), headersFromBaseOptions), options.headers);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         *
         * @summary Get Current Hashrate
         * @param {number} [timespan]
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCurrentHashrateStatsInfoHashrateCurrentGet: async (timespan, options = {}) => {
            const localVarPath = `/stats/info/hashrate/current`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = Object.assign(Object.assign({ method: 'GET' }, baseOptions), options);
            const localVarHeaderParameter = {};
            const localVarQueryParameter = {};
            // authentication APIKeyHeader required
            await setApiKeyToObject(localVarHeaderParameter, "x-api-key", configuration);
            if (timespan !== undefined) {
                localVarQueryParameter['timespan'] = timespan;
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = Object.assign(Object.assign(Object.assign({}, localVarHeaderParameter), headersFromBaseOptions), options.headers);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         *
         * @summary Get Historic Hashrate
         * @param {number} fromTs
         * @param {number} [toTs]
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getHistoricHashrateStatsInfoHashrateHistoricGet: async (fromTs, toTs, options = {}) => {
            // verify required parameter 'fromTs' is not null or undefined
            assertParamExists('getHistoricHashrateStatsInfoHashrateHistoricGet', 'fromTs', fromTs);
            const localVarPath = `/stats/info/hashrate/historic`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = Object.assign(Object.assign({ method: 'GET' }, baseOptions), options);
            const localVarHeaderParameter = {};
            const localVarQueryParameter = {};
            // authentication APIKeyHeader required
            await setApiKeyToObject(localVarHeaderParameter, "x-api-key", configuration);
            if (fromTs !== undefined) {
                localVarQueryParameter['from_ts'] = fromTs;
            }
            if (toTs !== undefined) {
                localVarQueryParameter['to_ts'] = toTs;
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = Object.assign(Object.assign(Object.assign({}, localVarHeaderParameter), headersFromBaseOptions), options.headers);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    };
};
/**
 * DefaultApi - functional programming interface
 * @export
 */
export const DefaultApiFp = function (configuration) {
    const localVarAxiosParamCreator = DefaultApiAxiosParamCreator(configuration);
    return {
        /**
         *
         * @summary Get Balance And Group By Address
         * @param {string} address
         * @param {boolean} [mempool]
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getBalanceAndGroupByAddressStatsAddressesGet(address, mempool, options) {
            var _a, _b, _c;
            const localVarAxiosArgs = await localVarAxiosParamCreator.getBalanceAndGroupByAddressStatsAddressesGet(address, mempool, options);
            const index = (_a = configuration === null || configuration === void 0 ? void 0 : configuration.serverIndex) !== null && _a !== void 0 ? _a : 0;
            const operationBasePath = (_c = (_b = operationServerMap['DefaultApi.getBalanceAndGroupByAddressStatsAddressesGet']) === null || _b === void 0 ? void 0 : _b[index]) === null || _c === void 0 ? void 0 : _c.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
        /**
         *
         * @summary Get Current Hashrate
         * @param {number} [timespan]
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getCurrentHashrateStatsInfoHashrateCurrentGet(timespan, options) {
            var _a, _b, _c;
            const localVarAxiosArgs = await localVarAxiosParamCreator.getCurrentHashrateStatsInfoHashrateCurrentGet(timespan, options);
            const index = (_a = configuration === null || configuration === void 0 ? void 0 : configuration.serverIndex) !== null && _a !== void 0 ? _a : 0;
            const operationBasePath = (_c = (_b = operationServerMap['DefaultApi.getCurrentHashrateStatsInfoHashrateCurrentGet']) === null || _b === void 0 ? void 0 : _b[index]) === null || _c === void 0 ? void 0 : _c.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
        /**
         *
         * @summary Get Historic Hashrate
         * @param {number} fromTs
         * @param {number} [toTs]
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getHistoricHashrateStatsInfoHashrateHistoricGet(fromTs, toTs, options) {
            var _a, _b, _c;
            const localVarAxiosArgs = await localVarAxiosParamCreator.getHistoricHashrateStatsInfoHashrateHistoricGet(fromTs, toTs, options);
            const index = (_a = configuration === null || configuration === void 0 ? void 0 : configuration.serverIndex) !== null && _a !== void 0 ? _a : 0;
            const operationBasePath = (_c = (_b = operationServerMap['DefaultApi.getHistoricHashrateStatsInfoHashrateHistoricGet']) === null || _b === void 0 ? void 0 : _b[index]) === null || _c === void 0 ? void 0 : _c.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
    };
};
/**
 * DefaultApi - factory interface
 * @export
 */
export const DefaultApiFactory = function (configuration, basePath, axios) {
    const localVarFp = DefaultApiFp(configuration);
    return {
        /**
         *
         * @summary Get Balance And Group By Address
         * @param {string} address
         * @param {boolean} [mempool]
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getBalanceAndGroupByAddressStatsAddressesGet(address, mempool, options) {
            return localVarFp.getBalanceAndGroupByAddressStatsAddressesGet(address, mempool, options).then((request) => request(axios, basePath));
        },
        /**
         *
         * @summary Get Current Hashrate
         * @param {number} [timespan]
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCurrentHashrateStatsInfoHashrateCurrentGet(timespan, options) {
            return localVarFp.getCurrentHashrateStatsInfoHashrateCurrentGet(timespan, options).then((request) => request(axios, basePath));
        },
        /**
         *
         * @summary Get Historic Hashrate
         * @param {number} fromTs
         * @param {number} [toTs]
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getHistoricHashrateStatsInfoHashrateHistoricGet(fromTs, toTs, options) {
            return localVarFp.getHistoricHashrateStatsInfoHashrateHistoricGet(fromTs, toTs, options).then((request) => request(axios, basePath));
        },
    };
};
/**
 * DefaultApi - object-oriented interface
 * @export
 * @class DefaultApi
 * @extends {BaseAPI}
 */
export class DefaultApi extends BaseAPI {
    /**
     *
     * @summary Get Balance And Group By Address
     * @param {string} address
     * @param {boolean} [mempool]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    getBalanceAndGroupByAddressStatsAddressesGet(address, mempool, options) {
        return DefaultApiFp(this.configuration).getBalanceAndGroupByAddressStatsAddressesGet(address, mempool, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     *
     * @summary Get Current Hashrate
     * @param {number} [timespan]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    getCurrentHashrateStatsInfoHashrateCurrentGet(timespan, options) {
        return DefaultApiFp(this.configuration).getCurrentHashrateStatsInfoHashrateCurrentGet(timespan, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     *
     * @summary Get Historic Hashrate
     * @param {number} fromTs
     * @param {number} [toTs]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    getHistoricHashrateStatsInfoHashrateHistoricGet(fromTs, toTs, options) {
        return DefaultApiFp(this.configuration).getHistoricHashrateStatsInfoHashrateHistoricGet(fromTs, toTs, options).then((request) => request(this.axios, this.basePath));
    }
}
